const express = require('express');
const router = express.Router();
const multer=require("multer");
const authController = require('../controllers/authController');
const upload=require("../controllers/authController.js").upload;
router.post('/register',upload.single('profilepic'),authController.register);
router.post('/login', authController.login);
router.post('/refresh-token', authController.refreshToken);
router.post('/logout', authController.logout);
router.post('/forgot-password', authController.forgotPassword);
router.post('/reset-password/:token', authController.resetPassword);
router.get('/verify-email', authController.verifyEmail);
module.exports = router;
